djworkplace/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from .views import *
from django.views.generic.base import RedirectView
import os
from django.utils.translation import ugettext as _


admin.site.site_header = _("%s Admin") % settings.APP_NAME
admin.site.site_title = _("%s Admin Portal") % settings.APP_NAME
admin.site.index_title = _("Welcome to %s Admin Portal") % settings.APP_NAME


urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', Home.as_view(), name='home'),
    path('', RedirectView.as_view(pattern_name='staff:calendar'), name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('staff.urls')),
    path('holidays/', include('holidays.urls')),
]



if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

holidays/urls.py
from django.urls import path
from .views import *

app_name = 'holidays'

urlpatterns = [
   path('request_leave/', RequestLeave.as_view(), name='request-leave'),
]

staff/urls.py
from django.urls import path
from .views import *

app_name = 'staff'

urlpatterns = [
   path('calendar/', CalendarView.as_view(), name='calendar'),
   path('calendar/<int:year>-<int:month>/', CalendarView.as_view(), name='calendar'),
  ]

holidays/models.py
from django.conf import settings
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.core.exceptions import ValidationError
from django.db.models import Q
from django.utils import timezone
from datetime import datetime, timedelta
from staff.models import Location, Department
from django.contrib.auth import get_user_model
from .managers import *
from .utils import location_holiday_dates, is_working_day
import datetime

class LeaveType(models.Model):
    name = models.CharField(max_length=50, unique=True)
    icon = models.CharField(max_length=3)

    def __str__(self):
        return "%s %s" % (self.icon, self.name,)

    class Meta:
        ordering = ['name']
        verbose_name = _('leave type')
        verbose_name_plural = _('leave types')

class LeaveLimit(models.Model):
    department = models.ForeignKey(Department, on_delete=models.CASCADE, verbose_name=_('department'), related_name='leave_limits')
    location = models.ForeignKey(Location, on_delete=models.CASCADE, verbose_name=_('location'), related_name='leave_limits')
    type = models.ForeignKey(LeaveType, on_delete=models.PROTECT, verbose_name=_('type'), related_name='department_leaves')
    days = models.PositiveSmallIntegerField(verbose_name=_('days'), help_text=_('Yearly permission days for this type'))

    class Meta:
        ordering = ['department', 'location']
        verbose_name = _('leave limit')
        verbose_name_plural = _('leave limits')
        unique_together = (('department', 'location', 'type'),)

    def __str__(self):
        return "%d/%d/%d - %d" % (self.department_id, self.location_id, self.type_id, self.days)

class Leave(models.Model):
    calendar_template = 'holidays/leave_event.html'
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name=_('user'), related_name='leaves', editable=False)
    type = models.ForeignKey(LeaveType, on_delete=models.PROTECT, verbose_name=_('type'), related_name='leaves')
    start = models.DateField(_('start'))
    end = models.DateField(_('end'))
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    approval_date = models.DateTimeField(blank=True, null=True, editable=False)
    approved_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT, verbose_name=_('approved by'), related_name='vacation_approvals', blank=True, null=True, editable=False)
    notes = models.TextField(blank=True, max_length=500)
    year = models.PositiveSmallIntegerField(_('year'))

    def __str__(self):
        return "%d %s - %s" % (self.user_id, self.start, self.end)

    def dates(self):
        return (self.start + timedelta(days=d) for d in range((self.end - self.start).days + 1))

    def working_dates(self):
        return (d for d in self.dates() if is_working_day(d, self.user.staffprofile.location))

    def working_days(self):
        return len(list(self.working_dates()))

    def clean(self):
        super().clean()
        if not self.user.staffprofile.department:
            raise ValidationError('%s must be in a department first' % self.user)

        if self.end < self.start:
            raise ValidationError("End date can't be before start date")

        if min(self.start.year, self.end.year) < self.year:
            raise ValidationError("Leave dates must be in year %d" % self.year)

        max_date = datetime.date(self.year + 1, 4, 1) - datetime.timedelta(days=1)
        if self.end > max_date:
            raise ValidationError("Leaves for the %d period must be before %s" % (self.year, max_date))

        start_collision = Q(start__lte=self.start, end__gte=self.start)
        end_collision = Q(start__lte=self.end, end__gte=self.end)
        contained_collission = Q(start__gte=self.start, end__lte=self.end)
        collisions = Leave.objects.filter(user=self.user).exclude(pk=self.pk).filter(
            start_collision|end_collision|contained_collission
        )
        if collisions.exists():
            raise ValidationError('There are other leave requests with one or more days colliding')

        if self.approved_by:
            if not self.user.staffprofile.department.managers.filter(pk=self.approved_by.pk).exists():
                raise ValidationError('%s is not a manager of %s department' % (self.approved_by, self.user.staffprofile.department))

    def save(self, *args, **kwargs):
        if self.approved_by:
            if not self.approval_date:
                self.approval_date = timezone.now()
        else:
            self.approval_date = None
        return super().save(*args, **kwargs)

    class Meta:
        ordering = ['-start', '-end']
        verbose_name = _('leave')
        verbose_name_plural = _('leaves')

class PublicHoliday(models.Model):
    objects = PublicHolidayManager()
    calendar_template = 'holidays/holiday_event.html'
    date = models.DateField(_('date'))
    yearly = models.BooleanField(_('yearly'))
    name = models.CharField(_('name'), max_length=200)
    locations = models.ManyToManyField(Location, verbose_name=_('locations'), related_name='local_holidays')

    def __str__(self):
        return self.name
        
    class Meta:
        ordering = ['yearly', '-date']
        verbose_name = _('public holiday')
        verbose_name_plural = _('public holidays')

class UserLeave(get_user_model()):

    def year_approved_leaves(self, type, year):
        count = 0  
        for v in Leave.objects.filter(user=self, type=type).filter(year=year, approval_date__isnull=False):
            count += len(list(v.working_dates()))
        return count

    def year_pending_leaves(self, type, year):
        from holidays.models import Leave
        count = 0  
        for v in Leave.objects.filter(user=self, type=type).filter(year=year, approval_date__isnull=True):
            count += len(list(v.working_dates()))
        return count
    
    class Meta:
        proxy = True
        verbose_name = _('user leaves')
        verbose_name_plural = _('users leaves')

holidays/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from .models import *
from datetime import date

class LeaveForm(forms.ModelForm):

    year = forms.TypedChoiceField(label=_('year'), coerce=int)

    def __init__(self, *args, user, **kwargs):
        super().__init__(*args, **kwargs)
        self.instance.user = user
        self.fields['type'].queryset = self.fields['type'].queryset.filter(department_leaves__department=user.staffprofile.department)
        year = date.today().year
        max_date = datetime.date(year, 4, 1) - datetime.timedelta(days=1)
        if max_date > date.today():
            self.fields['year'].choices = ((year - 1, year - 1), (year, year),)
        else:
            self.fields['year'].choices = ((year, year),)



    class Meta:
        model = Leave
        fields = ['type', 'start', 'end', 'notes', 'year']
        widgets = {
            'start': forms.DateInput(attrs={'type': 'date'}),
            'end': forms.DateInput(attrs={'type': 'date'}),
        }


class AdminLeaveForm(forms.ModelForm):

    approve = forms.BooleanField(label=_('Approve request'), required=False, help_text=_('check if you want to approve this request'))

    class Meta:
        model = Leave
        fields = ['type', 'start', 'end', 'notes']

holidays/views.py
from django.views.generic.edit import CreateView
from django.contrib import messages
from .models import *
from .forms import *
from .utils import user_leave_summary
from django.urls import reverse
from django.contrib import messages
from django.db.models import Q
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from datetime import date



class RequestLeave(LoginRequiredMixin, CreateView):
    model = Leave
    form_class = LeaveForm

    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.staffprofile.department:
            messages.warning(request, "You need to be part of a deparment")
            return redirect('home')
        return super().dispatch(request, *args, **kwargs)

    def get_initial(self):
        initial = super().get_initial()
        initial['year'] = date.today().year
        return initial

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['leave_summaries'] = [ (label, user_leave_summary(self.request.user, choice)) for choice, label in  context['form'].fields['year'].choices ]
        return context

    def get_success_url(self):
        return reverse('staff:calendar', args=[self.object.start.year, self.object.start.month])

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.info(self.request, _('Your leave request has been sent'))
        return response

holidays/templates/holidays/event.html
{% load i18n %}
<div class="{{ event.approval_date|yesno:'bg-primary text-white,text-primary' }} border border-primary px-2 rounded d-flex justify-content-between{% if not forloop.last %} mb-1{% endif %}" title="{% if event.approval_date %}{% trans 'Request approved' %}{% else %}{% trans 'Request pending' %}{% endif %}">
	<span>☀️</span> <span>{{ event.user }}</span>
</div>

holidays/templates/holidays/holiday_event.html
{% load i18n %}
<div class="bg-success text-white border border-success px-2 rounded d-flex justify-content-between{% if not forloop.last %} mb-1{% endif %}" title="{{ event }}">
	<span>🌟</span> <span>{{ event }}</span>
</div>

holidays/templates/holidays/holiday_form.html
{% extends 'base.html' %}
{% load i18n bootstrap4 %}
{% block main %}
<main class="container my-auto">
	<div class="row">
		<div class="col-lg-6 offset-lg-3">
			<div class="jumbotron">
				<h1 class="text-center">{% trans "Holidays request" %}</h1>
				<form method="POST" action="{% url 'holidays:create' %}">
					{% csrf_token %}
					{% bootstrap_form form %}
					{% bootstrap_button _("Send request") button_type="submit" button_class="btn-primary" %}
				</form>
			</div>
		</div>
	</div>
</main>
{% endblock main %}

holidays/templates/holidays/leave_event.html
{% load i18n %}
{% with type=event.type %}
<div class="{{ event.approval_date|yesno:'bg-primary text-white,text-primary' }} border border-primary px-2 rounded d-flex justify-content-between{% if not forloop.last %} mb-1{% endif %}" title="{% if event.approval_date %}{% blocktrans %}{{ type }} approved{% endblocktrans %}{% else %}{% blocktrans %}{{ type }} request pending{% endblocktrans %}{% endif %}">
	<span>{{ event.type.icon }}</span> <span>{{ event.user }}</span>
</div>
{% endwith %}

holidays/templates/holidays/leave_form.html
{% extends 'base.html' %}
{% load i18n bootstrap4 %}
{% block main %}
<main class="container my-auto">
	<div class="row">
		<div class="col-lg-3 offset-lg-1">
			{% for year, leave_summary in leave_summaries %}
				<div class="card mb-3">
				  <div class="card-header">
				    {% blocktrans %}Your {{ year }} leaves{% endblocktrans %}
				  </div>
				  <ul class="list-group list-group-flush">
				  	{% for type, totals in leave_summary.items %}
				  	<li class="list-group-item">
				  		<p><strong>{{ type }}</strong></p>
				  		<ul class="small list-unstyled">
				  			<li>
				  				📅
					  			{% blocktrans count days=totals.total %}
					  			{{ days }} day per year
					  			{% plural %}
					  			{{ days }} days per year
					  			{% endblocktrans %}
				  			</li>
				  			<li class="text-success">
				  				✅
					  			{% blocktrans count days=totals.approved %}
					  			{{ days }} approved
					  			{% plural %}
					  			{{ days }} approved
					  			{% endblocktrans %}
				  			</li>
				  			<li class="text-warning">
				  				💬
					  			{% blocktrans count days=totals.pending %}
					  			{{ days }} pending approval
					  			{% plural %}
					  			{{ days }} pending approval
					  			{% endblocktrans %}
				  			</li>
				  			<li class="text-info">
				  				⭐
				  				{% blocktrans count days=totals.available %}
					  			{{ days }} available
					  			{% plural %}
					  			{{ days }} available
					  			{% endblocktrans %}
				  			</li>
				  		</ul>
				  	</li>
				  	{% endfor %}
				  </ul>
				</div>
			{% endfor %}
		</div>
		<div class="col-lg-6">
			<div class="jumbotron">
				<h1 class="text-center">{% trans "Vacations request" %}</h1>
				<form method="POST" action="{% url 'holidays:request-leave' %}">
					{% csrf_token %}
					{% bootstrap_form form %}
					{% bootstrap_button _("✔️ Send request") button_type="submit" button_class="btn-primary" %}
				</form>
			</div>
		</div>
	</div>
</main>
{% endblock main %}

holidays/templates/holidays/vacation_form.html
{% extends 'base.html' %}
{% load i18n bootstrap4 %}
{% block main %}
<main class="container my-auto">
	<div class="row">
		<div class="col-lg-3 offset-lg-1">
			<div class="card">
			  <div class="card-header">
			  	{% now "Y" as current_year %}
			    {% blocktrans %}Your {{ current_year }} vacations{% endblocktrans %}
			  </div>
			  <ul class="list-group list-group-flush">
			  	<li class="list-group-item">{% blocktrans with total=user.staffprofile.department.vacations %}{{ total}} per year{% endblocktrans %}</li>
			    <li class="list-group-item">{% blocktrans %}{{ approved }} approved{% endblocktrans %}</li>
			    <li class="list-group-item">{% blocktrans %}{{ pending }} pending approval{% endblocktrans %}</li>
			    <li class="list-group-item">{% blocktrans %}{{ available }} available{% endblocktrans %}</li>
			  </ul>
			</div>
		</div>
		<div class="col-lg-6">
			<div class="jumbotron">
				<h1 class="text-center">{% trans "Vacations request" %}</h1>
				<form method="POST" action="{% url 'holidays:create-vacations' %}">
					{% csrf_token %}
					{% bootstrap_form form %}
					{% bootstrap_button _("Send request") button_type="submit" button_class="btn-primary" %}
				</form>
			</div>
		</div>
	</div>
</main>
{% endblock main %}